from app import get_db, upsert_sample, utc_now


DEMO_SAMPLES = [
    {
        "sample_id": "WWM-DEMO-CO-001",
        "collector_name": "Demo collector",
        "sampling_date": "2026-05-01",
        "country": "CO",
        "site_name": "Bogota highland plot",
        "lat": 4.711,
        "lon": -74.072,
        "altitude_m": 2640,
        "gps_accuracy_m": 12,
        "what3words": "demo.bogota.plot",
        "what3words_source": "manual",
        "what3words_status": "demo",
        "what3words_language": "en",
        "what3words_map_url": "https://w3w.co/demo.bogota.plot",
        "what3words_nearest_place": "Bogota, Colombia",
        "what3words_country": "CO",
        "what3words_square_json": None,
        "what3words_updated_at": None,
        "affiliation": "worm_lab",
        "affiliation_other": None,
        "habitat_type": "agricultural_field",
        "habitat_other": None,
        "soil_types": "loam,clay",
        "soil_type_other": None,
        "soil_ph": 6.4,
        "climate_info": "Demo: cool tropical highland climate",
        "depth_cm": 15,
        "num_samples": 5,
        "photo_sample": None,
        "notes": "Demo record for map testing.",
        "raw_payload": "{}",
    },
    {
        "sample_id": "WWM-DEMO-CH-001",
        "collector_name": "Demo collector",
        "sampling_date": "2026-05-04",
        "country": "CH",
        "site_name": "Basel grassland edge",
        "lat": 47.5596,
        "lon": 7.5886,
        "altitude_m": 280,
        "gps_accuracy_m": 8,
        "what3words": "demo.basel.grassland",
        "what3words_source": "manual",
        "what3words_status": "demo",
        "what3words_language": "en",
        "what3words_map_url": "https://w3w.co/demo.basel.grassland",
        "what3words_nearest_place": "Basel, Switzerland",
        "what3words_country": "CH",
        "what3words_square_json": None,
        "what3words_updated_at": None,
        "affiliation": "worm_lab,sanger_institute",
        "affiliation_other": None,
        "habitat_type": "grassland",
        "habitat_other": None,
        "soil_types": "loam,sandy",
        "soil_type_other": None,
        "soil_ph": 7.1,
        "climate_info": "Demo: temperate seasonal climate",
        "depth_cm": 20,
        "num_samples": 4,
        "photo_sample": None,
        "notes": "Demo record for pH and family filters.",
        "raw_payload": "{}",
    },
    {
        "sample_id": "WWM-DEMO-KE-001",
        "collector_name": "Demo collector",
        "sampling_date": "2026-05-08",
        "country": "KE",
        "site_name": "Nairobi urban garden",
        "lat": -1.2864,
        "lon": 36.8172,
        "altitude_m": 1795,
        "gps_accuracy_m": 15,
        "what3words": "demo.nairobi.garden",
        "what3words_source": "manual",
        "what3words_status": "demo",
        "what3words_language": "en",
        "what3words_map_url": "https://w3w.co/demo.nairobi.garden",
        "what3words_nearest_place": "Nairobi, Kenya",
        "what3words_country": "KE",
        "what3words_square_json": None,
        "what3words_updated_at": None,
        "affiliation": "crc1211",
        "affiliation_other": None,
        "habitat_type": "urban",
        "habitat_other": None,
        "soil_types": "mixed",
        "soil_type_other": None,
        "soil_ph": 6.8,
        "climate_info": "Demo: subtropical highland climate",
        "depth_cm": 10,
        "num_samples": 3,
        "photo_sample": None,
        "notes": "Demo urban garden sample.",
        "raw_payload": "{}",
    },
    {
        "sample_id": "WWM-DEMO-JP-001",
        "collector_name": "Demo collector",
        "sampling_date": "2026-05-11",
        "country": "JP",
        "site_name": "Honshu forest soil",
        "lat": 35.6762,
        "lon": 139.6503,
        "altitude_m": 40,
        "gps_accuracy_m": 10,
        "what3words": "demo.honshu.forest",
        "what3words_source": "manual",
        "what3words_status": "demo",
        "what3words_language": "en",
        "what3words_map_url": "https://w3w.co/demo.honshu.forest",
        "what3words_nearest_place": "Tokyo, Japan",
        "what3words_country": "JP",
        "what3words_square_json": None,
        "what3words_updated_at": None,
        "affiliation": "sanger_institute",
        "affiliation_other": None,
        "habitat_type": "forest",
        "habitat_other": None,
        "soil_types": "volcanic,loam",
        "soil_type_other": None,
        "soil_ph": 5.6,
        "climate_info": "Demo: humid temperate climate",
        "depth_cm": 18,
        "num_samples": 6,
        "photo_sample": None,
        "notes": "Demo forest sample.",
        "raw_payload": "{}",
    },
    {
        "sample_id": "WWM-DEMO-ZA-001",
        "collector_name": "Demo collector",
        "sampling_date": "2026-05-16",
        "country": "ZA",
        "site_name": "Cape coastal dune",
        "lat": -33.9249,
        "lon": 18.4241,
        "altitude_m": 25,
        "gps_accuracy_m": 18,
        "what3words": "demo.cape.dune",
        "what3words_source": "manual",
        "what3words_status": "demo",
        "what3words_language": "en",
        "what3words_map_url": "https://w3w.co/demo.cape.dune",
        "what3words_nearest_place": "Cape Town, South Africa",
        "what3words_country": "ZA",
        "what3words_square_json": None,
        "what3words_updated_at": None,
        "affiliation": "worm_lab",
        "affiliation_other": None,
        "habitat_type": "coastal",
        "habitat_other": None,
        "soil_types": "sandy",
        "soil_type_other": None,
        "soil_ph": 8.0,
        "climate_info": "Demo: mediterranean coastal climate",
        "depth_cm": 12,
        "num_samples": 5,
        "photo_sample": None,
        "notes": "Demo coastal sample.",
        "raw_payload": "{}",
    },
]


DEMO_TAXA = [
    ("WWM-DEMO-CO-001", "Pratylenchus penetrans", "Pratylenchidae", "species", "morphological"),
    ("WWM-DEMO-CO-001", "Meloidogyne incognita", "Meloidogynidae", "species", "molecular"),
    ("WWM-DEMO-CH-001", "Heterodera schachtii", "Heteroderidae", "species", "morphological"),
    ("WWM-DEMO-KE-001", "Caenorhabditis elegans", "Rhabditidae", "species", "molecular"),
    ("WWM-DEMO-JP-001", "Aphelenchoides fragariae", "Aphelenchoididae", "species", "morphological"),
    ("WWM-DEMO-ZA-001", "Panagrolaimus sp.", "Panagrolaimidae", "genus", "morphological"),
]


def main() -> None:
    now = utc_now()
    created = 0
    for sample in DEMO_SAMPLES:
        _, was_created = upsert_sample(sample)
        created += int(was_created)

    with get_db() as conn:
        for sample_id, scientific_name, family, rank, method in DEMO_TAXA:
            conn.execute(
                """
                INSERT INTO sample_taxa
                  (sample_id, scientific_name, family, rank, source, identification_method,
                   curator_name, validation_date, created_at)
                VALUES (?, ?, ?, ?, 'curated', ?, 'Demo seed', DATE('now'), ?)
                ON CONFLICT(sample_id, scientific_name, family, source) DO UPDATE SET
                  rank=excluded.rank,
                  identification_method=excluded.identification_method,
                  curator_name=excluded.curator_name,
                  validation_date=excluded.validation_date
                """,
                (sample_id, scientific_name, family, rank, method, now),
            )
    print(f"Seeded {len(DEMO_SAMPLES)} demo samples ({created} new).")


if __name__ == "__main__":
    main()
